config:
  PREVIOUS_DB_INIT: '20240301144900'
dev_lite:
  DB_AUTH: sqlite:///server/langman.db
  DB_GAMES: sqlite:///server/langman.db
  DB_USAGE: sqlite:///server/usages.db
dev_postgres:
  DB_AUTH: postgresql://localhost:5432/langman
  DB_GAMES: postgresql://localhost:5432/langman
  DB_USAGE: sqlite:///server/usages.db
heroku:
  DB_USAGE: sqlite:///server/usages.db
  DB_GAMES: env:DATABASE_URL
  DB_AUTH: env:DATABASE_URL